trains:
  - name: train_05/04/2023_before
    type: before
    departure_date: 2023-04-05T20:25
    origin: FRPNO
    destination: FRADJ

  - name: train_05/04/2023_train
    type: train
    departure_date: 2023-04-05T18:16
    origin: FRPNO
    destination: FRADJ

  - name: train_05/04/2023_after
    type: after
    departure_date: 2023-04-05T17:00
    origin: FRPNO
    destination: FRADJ
    
  # To implement  
  # - name: train_05/04/2023_between
  #   type: between
  #   departure_date_from: 2023-04-05T17:00
  #   departure_date_to: 2023-04-05T19:00
  #   origin: FRPNO
  #   destination: FRADJ

notification:
    telegram:
      API_KEY: "YourTelegramAPIKeyHere" # Follow steps here : https://sendpulse.com/knowledge-base/chatbot/telegram/create-telegram-chatbot
      user_id_to_notify: "YourIDHere" # To get you id use : https://web.telegram.org/a/#1157763503
      message_format: '''%SYMBOL %TRAIN_DATE at %TRAIN_DEPARTURE_TIME (%TRAIN_NAME) - %TRAIN_ORIGIN > %TRAIN_DESTINATION | %TRAIN_FREE_PLACES_LEFT remaining  (updated at: %UPDATE_DATETIME, requestID: %REQUEST_NUMBER)'''
      symbol_less_5_places_left: "🔴"
      symbol_6_to_10_places_left: "🟠"
      symbol_11_to_20_places_left: "🔵"
      symbol_more_20_places_left: "🟢"
