trains:

# (29/03/2023)
  - name: Retour Paris 18h16 (29/03/2023)
    type: train
    departure_date: 2023-03-29T18:16
    origin: FRPNO
    destination: FRADJ

  - name: Retour Paris 18h46 (29/03/2023)
    type: train
    departure_date: 2023-03-29T18:46
    origin: FRPNO
    destination: FRADJ

# (05/04/2023)
  - name: Retour Paris 18h16 (05/04/2023)
    type: train
    departure_date: 2023-04-05T18:16
    origin: FRPNO
    destination: FRADJ
    
  - name: Retour Paris 18h46 (05/04/2023)
    type: train
    departure_date: 2023-04-05T18:46
    origin: FRPNO
    destination: FRADJ

  - name: Retour Paris 17h52 (05/04/2023)
    type: train
    departure_date: 2023-04-05T17:52
    origin: FRPNO
    destination: FRADJ

# (12/04/2023)
  - name: Retour Paris 18h16 (12/04/2023)
    type: train
    departure_date: 2023-04-12T18:16
    origin: FRPNO
    destination: FRADJ
    
  - name: Retour Paris 18h46 (12/04/2023)
    type: train
    departure_date: 2023-04-12T18:46
    origin: FRPNO
    destination: FRADJ

  - name: Retour Paris 17h52 (12/04/2023)
    type: train
    departure_date: 2023-04-12T17:52
    origin: FRPNO
    destination: FRADJ

# (09/04/2023)
  - name: Aller Paris 17h42 (09/04/2023)
    type: train
    departure_date: 2023-04-09T17:42
    origin: FRADJ
    destination: FRPNO

  - name: Aller Paris 17h51 (09/04/2023)
    type: train
    departure_date: 2023-04-09T17:51
    origin: FRADJ
    destination: FRPNO

  - name: Aller Paris 18h12 (09/04/2023)
    type: train
    departure_date: 2023-04-09T18:12
    origin: FRADJ
    destination: FRPNO

  # - name: Aller Paris 19h12 (09/04/2023)
  #   type: train
  #   departure_date: 2023-04-09T19:12
  #   origin: FRADJ
  #   destination: FRPNO

# (16/04/2023)
  - name: Aller Paris 17h42 (16/04/2023)
    type: train
    departure_date: 2023-04-16T17:42
    origin: FRADJ
    destination: FRPNO

  - name: Aller Paris 17h51 (16/04/2023)
    type: train
    departure_date: 2023-04-16T17:51
    origin: FRADJ
    destination: FRPNO

  - name: Aller Paris 18h12 (16/04/2023)
    type: train
    departure_date: 2023-04-16T18:12
    origin: FRADJ
    destination: FRPNO

  - name: Aller Paris 19h12 (16/04/2023)
    type: train
    departure_date: 2023-04-16T19:12
    origin: FRADJ
    destination: FRPNO