trains:
  - name: train_05/04/2023_before
    type: before
    departure_date: 2023-04-05T20:25
    origin: FRPNO
    destination: FRADJ

  - name: train_05/04/2023_train
    type: train
    departure_date: 2023-04-05T18:16
    origin: FRPNO
    destination: FRADJ

  - name: train_05/04/2023_after
    type: after
    departure_date: 2023-04-05T17:00
    origin: FRPNO
    destination: FRADJ
    
  # To implement  
  # - name: train_05/04/2023_between
  #   type: between
  #   departure_date_from: 2023-04-05T17:00
  #   departure_date_to: 2023-04-05T19:00
  #   origin: FRPNO
  #   destination: FRADJ


